all: programme_1 programme_2 main

programme_1: programme_1.c
	gcc -o programme_1 programme_1.c

programme_2: programme_2.c
	gcc -o programme_2 programme_2.c

main: main.c
	gcc -o main main.c

clean:
	rm -f *.o
