all: exemple_arguments exemple_getoptlong

exemple_arguments : exemple_arguments.c
	gcc -o exemple_arguments exemple_arguments.c

exemple_getoptlong : exemple_getoptlong.c
	gcc -o exemple_getoptlong exemple_getoptlong.c

clean:
	rm -f *.o
